# Generated by Django 4.2.17 on 2024-12-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card_generation')},
        ),
    ]
